config/routes.rb
WeddingDraft::Application.routes.draw do
  match '/:locale', to: 'static_pages#home', via: 'get'
  root 'static_pages#home'
  scope "/:locale" do
    resources :password_resets
    resources :users
    resources :sessions, only: [:new, :create, :destroy]
    match '/home', to: 'static_pages#home', via: 'get'
    match '/registration', to: 'users#new', via: 'get'
    match '/signin', to: 'sessions#new', via: 'get'
    match '/signout', to: 'sessions#destroy', via: 'delete'
    match '/program', to: 'static_pages#program', via: 'get'
    match '/locations', to: 'static_pages#locations', via: 'get'
    match '/hotels', to: 'static_pages#hotels', via: 'get'
    match '/region', to: 'static_pages#region', via: 'get'
    match '/registry', to: 'static_pages#registry', via: 'get'
    match '/rsvp', to: 'static_pages#rsvp', via: 'get'
    match '/contact', to: 'static_pages#contact', via: 'get'
    match '/germanvsenglish', to: 'static_pages#germanvsenglish', via: 'get'
  end

  

end

app/models/user.rb
class User < ActiveRecord::Base
  before_create { generate_token(:remember_token) }
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX },
            uniqueness: {case_sensitive: false}
  validates :password, length: { minimum: 6 }
  has_secure_password
    
  def User.new_remember_token
      SecureRandom.urlsafe_base64
  end
  
  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end
  
  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!(:validate => false)
    UserMailer.password_reset(self).deliver
  end

  def send_welcome
    UserMailer.welcome(self).deliver
  end
  
  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :signed_in_user
  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
    
  def default_url_options(options={})
    logger.debug "default_url_options is passed options: #{options.inspect}\n"
    { locale: I18n.locale }
  end

  private 
    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_path, locale: I18n.locale, notice: t(:please_sign_in)
      end
    end
    
    def correct_user
      @user=User.find(params[:id])
      redirect_to home_path, locale: I18n.locale unless current_user?(@user) or current_user.admin?
    end
    
    def admin_user
      redirect_to home_path, locale: I18n.locale unless current_user.admin?
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
    
  
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  skip_before_action :signed_in_user
  
  def new
  end
  
  def create
    user = User.find_by_email(params[:user][:email])
    user.send_password_reset if user
    redirect_to root_url, :notice => t(:password_reset_mail_sent)
  end
  
  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end
  
  def update
    @user = User.find_by_password_reset_token!(params[:id])
    if @user.password_reset_sent_at < 24.hours.ago
      redirect_to new_password_reset_path, :alert => t(:password_reset_expired)
    elsif @user.update_attributes(user_params)
      sign_in @user
      redirect_to root_url, :notice => t(:password_reset_success)
    else
      render :edit
    end
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :signed_in_user, except: [:destroy]

  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      flash[:success] = t(:welcome_back) + user.name
      redirect_back_or home_path
    else
      flash.now[:error] = t(:invalid_password)
      render 'new'
    end
  end
  
  def destroy
    sign_out
    redirect_to home_path
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :signed_in_user, only: [:home]

  def home
  end

  def program
  end

  def locations
  end

  def hotels
  end

  def region
  end

  def registry
  end

  def rsvp
  end

  def contact
  end

  def germanvsenglish
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :signed_in_user, except: [:edit, :destroy, :index, :update]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:index, :destroy]
  
  def new
    @user = User.new
  end
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      @user.send_welcome
      flash[:success] = t(:welcome) + @user.name
      redirect_to root_path
    else
      render 'new'
    end
  end
  
  def update 
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to edit_user_path(@user)
    else
      render 'edit'
    end
  end
  
  def edit
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user=user
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def sign_out
    self.current_user =nil
    cookies.delete(:remember_token)
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end
  
  def store_location
    session[:return_to] = request.url
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_countdown.html.erb
<div class="col-md-2 pull-left center">
	<h2><strong><%= ((Time.gm(2014, 6, 14, 12, 00, 00)-Time.now)/86400).round %></strong><br><%= t 'days_left' %></h2>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer navbar-fixed-bottom navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<nav>
				<ul class="pull-right">
					<% if current_user.admin? %>
						<li><%= link_to "Users", users_path %></li>
					<% end %>
					<li><%= link_to t(:my_profile), edit_user_path(current_user) %></li>
					<li><%= link_to t(:contact_us), contact_path %></li>
					<li><%= link_to t(:sign_out), signout_path, method: "delete" %></li>
				</ul>
			</nav>
		</div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to t(:s_p_wedding), home_path, id: "logo", class: "navbar-brand visible-lg visible-md" %>
      <%= link_to "S & P", home_path, id: "logo", class: "navbar-brand visible-xs visible-sm" %>
    </div>
    <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
			<li class="visible-lg"><%= link_to t(:home), home_path %></li>
			<% if signed_in? %>
				<li><%= link_to t(:program), program_path %></li>
				<li><%= link_to t(:locations), locations_path %></li>
				<li><%= link_to t(:hotels), hotels_path %></li>
				<li class="hidden-sm"><%= link_to t(:wedding), germanvsenglish_path %></li>
				<li class="hidden-sm"><%= link_to t(:region), region_path %></li>
				<li class="hidden-sm"><%= link_to t(:registry), registry_path %></li>
				<li class="hidden-sm"><%= link_to t(:rsvp), rsvp_path %></li>
				<li class="dropdown visible-sm">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t(:more) %> <b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><%= link_to t(:wedding), germanvsenglish_path %></li>
						<li><%= link_to t(:region), region_path %></li>
						<li><%= link_to t(:registry), registry_path %></li>
						<li><%= link_to t(:rsvp), rsvp_path %></li>
					<ul>
				</li>
			<% else %>
				<li><%= link_to t(:sign_in), signin_path %></li>
				<li><%= link_to t(:register), registration_path %></li>
			<% end %>
		</ul>
	</div>
</nav>

app/views/password_resets/edit.html.erb
<% provide(:title, t(:reset_password))%>
<h1><%= t(:reset_password)%></h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for @user, url: password_reset_path(id: params[:id]) do |f| %>
			<div class="form-group">
			    <%= f.label :password, t(:password)%>
			    <%= f.password_field :password, class: 'form-control'  %>
			</div>
			<div class="form-group">
			    <%= f.label :password_confirmation, t(:password_confirmation) %>
			    <%= f.password_field :password_confirmation, class: 'form-control'  %>
			</div>

			<%= f.submit t(:update_password), class: "btn btn-lg btn-primary"%>

		<% end %>
	</div>
</div>

app/views/password_resets/new.html.erb
<% provide(:title, t(:reset_password))%>
<h1><%=	t(:reset_password) %></h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(:user, url: password_resets_path) do |f| %>
		<div class="form-group">
			<%=	f.label :email%>
			<%=	f.text_field :email, class: 'form-control' %>
		</div>

			<%= f.submit t(:reset_password), class: "btn btn-lg btn-primary"%>
		<% end%>
	</div>
</div>

app/views/static_pages/home.de.html.erb
<% provide(:title, "Willkommen auf unserer Hochzeits-Homepage!") %>

<h1>Willkommen auf unserer Hochzeits-Homepage!</h1>

<div class="script"><h2><p>Liebe Familie und Freunde,</p></h2></div>

<p>Wir freuen uns, dass Ihr den Weg auf unsere Homepage gefunden habt und können es kaum erwarten,<% if signed_in? %> am 14. Juni 2014<% end %> unsere Hochzeit mit Euch zu feiern.</p>
	
<% if signed_in? %>

<%= image_tag("pic01.jpg", class: "left inline") %>
	<p>Uns ist bewusst, dass viele von Euch eine lange Anreise haben werden. Um Euch bei der Planung zu unterstützen, haben wir ein wenig recherchiert und nachgeforscht und die wichtigsten Informationen hier zusammengefasst. </p>

	<p>Hier könnt Ihr <%= link_to "Details", program_path %> lesen bzgl. was, wann und wo stattfindet und wie man am besten zu den <%= link_to "verschiedenen Lokalitäten", locations_path %> findet. </p>

	<p>Desweiteren gibt es Hinweise zu <%= link_to "Übernachtungsmöglichkeiten", hotels_path %> in der Umgebung, welche <%= link_to "schönen Dinge", region_path %> man im Rheingau unternehmen kann und was wir uns zum  <%= link_to "Dresscode", program_path %> überlegt haben.</p>

	<p>Für unsere englischen Gäste haben wir auch eine kleine Zusammenfassung geschrieben, inwiefern sich <%= link_to "eine deutsche und eine englische Hochzeit", germanvsenglish_path %> unterscheiden. Dies mag fuer Euch Deutsche nicht so wichtig sein, da ihr eigentlich alle mit der deutschen Tradition vertraut sein solltet, aber wenn Ihr daran interessiert seid, könnt ihr auch dort mal herumstöbern. </p>

	<p>Sobald wir die Einzelheiten unserer <%= link_to "Hochzeitsliste", registry_path %> arrangiert haben, werdet Ihr hier auch einen Link zu dieser Seite finden können.  Außerdem gibt es dann auch noch die Möglichkeit zur Hochzeit <%= link_to "zu- und abzusagen", rsvp_path %> und natürlich direkt mit <%= link_to "uns in Kontakt", contact_path %> zu treten. </p>

	<p>Wir freuen uns über jede Nachricht!</p>
		
<% else %>
	<p>Um zu vermeiden, dass sich zu viele ungebetene Besucher hier auf der Homepage umschauen, wären wir Euch dankbar, wenn Ihr Euch kurz registrieren würdet. Das dauert gar nicht lange und es muss auch nur einmal gemacht werden. </p>
	
<% end %>
<div class="script"><h2><p>Vielen Dank und viele liebe Grüße</p>

<p>Steffi und Phil</p></h2></div>

<% if not signed_in? %>
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<%= link_to "Anmelden", signin_path, class: "btn btn-lg btn-default" %>
			<%= link_to "Registrieren", registration_path, class: "btn btn-lg btn-primary" %>
		</div>
	</div>
<% end %>

app/views/static_pages/home.html.erb
<% provide(:title, "Welcome to our Wedding Website") %>

<h1>Welcome to our Wedding Website!</h1>

<div class="script"><h2><p>Dear family and friends,</p></h2></div>

<p>We’re glad that you found your way to this homepage and are excited to celebrate our wedding with you<% if signed_in? %> on 14 June 2014<% end %>.</p>

<% if signed_in? %>

<%= image_tag("pic01.jpg", class: "left inline img-rounded img-responsive") %>
	<p>We appreciate that quite a lot of you will have to travel to come to Burg Schwarzenstein so to make it as easy as possible for you, we have done some research and summarized key information on this homepage.</p>

	<p>You can find <%= link_to "details", program_path %> on what will take place, when and where, how to get to the different <%= link_to "venues", locations_path %>, what <%= link_to "hotels", hotels_path %> are in the area and a little bit of information on the <%= link_to "dresscode", program_path %>. </p>

	<p>In addition, we also provide you with a brief overview of differences between an <%= link_to "English and a German wedding", germanvsenglish_path %>, which will be especially important for our guests from the UK. Don’t worry, it’s nothing too major, there will still be a white dress and a lovely celebration, but there are just a few things we want to point out so you know what is going on. </p>

	<p>For those of you thinking about spending a few more days in the region, we have included some details on <%= link_to "the region", region_path %> and made some suggestions as to what you can explore and what you shouldn’t miss. </p>

	<p>Once we have confirmed all the details and finalized the list, you will find a link to our <%= link_to "gift registry", registry_path %> from here, so please keep checking back. 	Finally, we include a place to <%= link_to "RSVP", rsvp_path %> and <%= link_to "contact us", contact_path %>.</p> 
	
	<p>We hope you enjoy exploring the details and find some answers, but please feel free to <%= link_to "contact us", contact_path %> directly with any questions or suggestions. </p>

<% else %>
	<p>Just so we can avoid too many random visitors we ask that you quickly register your name and email address with us.  If you've already done that you can just sign in instead.</p>
	
<% end %>
<div class="script"><h2><p>Thanks</p>

<p>Steffi and Phil</p></h2></div>

<% if not signed_in? %>
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<%= link_to "Sign in", signin_path, class: "btn btn-lg btn-default" %>
			<%= link_to "Register", registration_path, class: "btn btn-lg btn-primary" %>
		</div>
	</div>
<% end %>

app/views/static_pages/locations.de.html.erb
<% provide(:title, "Lokalitäten") %>
<h1>Lokalitäten</h1>

<p>Da heutzutage fast alle Autos SatNav haben und die meisten von uns mindestens ein Smartphone immer bei sich haben, könnte man meinen, dass es nicht mehr notwendig ist, eine Wegbschreibung anzubieten. </p>

<p>Aus eigener Erfahrung wissen wir allerdings, dass es hilfreich ist, wenn man alle wichtigen Adressen auf einen Blick hat und wenigstens schon mal so grob weiß, wo es hingeht. Deswegen haben wir auf dieser Seite die Adressen aller Orte zusammengetragen, an denen Festivitäten stattfinden. Außerdem findet ihr ein paar Tips, wie man am besten in den Rheingau kommt. </p>

<p>Informationen zur Lage von verschiedenen Hotels findet ihr auf der <%= link_to "Hotel Seite", hotels_path %>.</p>

<div class="row">
	<div class="col-md-6">
		<p><strong>Lokalität für Freitagabend:  </strong><br>
		Weingut Ankermühle<br>
		Kapperweg 1<br>
		65375 Oestrich-Winkel</p>

		<p><strong>Kirche am Samstag:</strong><br>
		Evangelische Kirche Geisenheim<br>
		Winkeler Straße 83<br>
		65366 Geisenheim</p>

		<p><strong>Lokalität für den Empfang nach der Kirche, die Feier am Samstagabend und das Frühstück am Sonntagmorgen:</strong><br>
		Burg Schwarzenstein<br>
		Rosengasse 32<br>
		65366 Geisenheim - Johannisberg<br></p>
	</div>
	<div class="col-md-4 col-md-offset-2">
		<%= image_tag("pic04.jpg", class: "right inline") %>
	</div>
</div>

<div>
	<iframe width=100% height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps/ms?msid=213619935787981326362.0004dd16626bc9fcb8416&amp;msa=0&amp;dg=feature&amp;ie=UTF8&amp;t=m&amp;ll=49.998912,7.975388&amp;spn=0.077241,0.205994&amp;z=12&amp;output=embed"></iframe><br />
	Für eine größere Ansicht der Karte bitte <a href="https://maps.google.com/maps/ms?msid=213619935787981326362.0004dd16626bc9fcb8416&amp;msa=0&amp;dg=feature&amp;ie=UTF8&amp;t=m&amp;ll=49.998912,7.975388&amp;spn=0.077241,0.205994&amp;z=12&amp;source=embed">hier</a> klicken.
</div><br>

<p><strong>Anreise per Flugzeug:</strong></p>

<p>Wer erst einmal die großen Distanzen per Flugzeug bewältigen will, steuert am besten Frankfurt International Airport oder Frankfurt Hahn Airport an. </p>

<ul><li><p>Der <a href="http://www.frankfurt-airport.com/content/frankfurt_airport/de.html">Internationale Flughafen Frankfurt</a> liegt etwa 51km von Burg Schwarzenstein entfernt und wird von den meisten großen und bekannten Airlines angeflogen.</p></li>

<li><p><a href="http://www.hahn-airport.de/">Frankfurt Hahn</a> liegt gut 100km entfernt und wird eigentlich nur von Ryanair angeflogen. </p></li></ul>

<p>Wenn Ihr an einem dieser Flughäfen gelandet seid, stellt sich die Frage, ob Ihr Euch ein Auto mietet oder Euch mit öffentlichen Verkehrsmitteln weiter vorkämpft. Solltet Ihr in Frankfurt Hahn landen, empfehlen wir Euch, ein Auto zu mieten, denn die Anbindung mit öffentlichen Verkehrsmitteln ist dort doch verbesserungsfähig.</p>

<p>Alle größeren Auto-Vermietungsgesellschaften sind an beiden Flughäfen vertreten, und so geht es eigentlich ganz leicht, ein Auto zu mieten: <a href="http://www.hertz.com/">Hertz</a>, <a href="http://www.sixt.com/">Sixt</a> or <a href="http://www.europcar.com/">Europcar</a>.</p>

<p>Solltet Ihr Euch entscheiden, Euch vom Internationalen Flughafen Frankfurt mit öffentlichen Verkehrsmitteln weiter vorzuarbeiten, dann macht Ihr das am besten wie folgt:
Mit den <a href="http://www.rmv.de/">S-Bahnen</a> S8 oder S9 bis zum Hauptbahnhof Wiesbaden fahren und dort auf die <a href="http://www.rheingaulinie.de/fahrplan">Rheingau-Linie</a> umsteigen. Diese hält unter anderem auch in Geisenheim, wo Ihr am besten aussteigt, um zu den Hotels und anderen Lokalitäten zu gelangen. </p>

<p><strong>Anreise per Bahn:</strong></p>

<p>Wenn Ihr Euch entscheidet, per Bahn anzureisen, steuert Ihr am besten erstmal die Hauptbahnhöfe in Wiesbaden oder Frankfurt an. Auf <a href="http://www.bahn.com/de">http://www.bahn.com/de</a> könnt ihr nach Verbindungen suchen.</p>

<p>An beiden Bahnhöfen könnt Ihr dann auf die <a href="http://www.rheingaulinie.de/fahrplan">Rheingau-Linie</a> umsteigen, die Euch wie oben beschrieben bis nach Geisenheim bringt.</p>

<p><strong>Anreise per Auto: </strong></p>
<p>Solltet Ihr mit dem Auto anreisen, dann gebt am besten die Postleitzahl Eures Hotels oder von Burg Schwarzenstein ins Navigations-System ein und folgt den Anweisungen!</p>

<p>Wenn Ihr erst einmal im Umfeld von Geisenheim seid, dann könnt Ihr die Karten, die wir oben und auf der Hotel-Page eingefügt habt, verwenden, um alles zu finden.</p>

<p><strong>Taxiunternehmen vor Ort</strong></p>
<p>Solltet Ihr im Laufe des Wochenendes ein Taxi brauchen, dann wendet Euch bitte an die folgenden Unternehmen:</p>

<p>Taxi Locke: +49 (0) 6722 - 3333</p>
<p>Taxi Wagner: +49 (0) 177 - 5407973</p>

app/views/static_pages/locations.html.erb
<% provide(:title, "Locations") %>
<h1>Locations</h1>

<p>In the time of smartphones and SatNav systems, it might be a little bit outdated to provide details on how to get somewhere, but we still wanted to give you an overview of the different ways to get there and what approach we recommend to make the planning a little bit easier for you. </p>

<p>Here are all the key locations for the event itself, they're all very close together and you can use the map to help with directions between them or from your starting location.</p>

<p>For help finding hotels please visit the <%= link_to "hotels page", hotels_path %> and for ideas on things to do in <%= link_to "the region", region_path %> please visit the page on <%= link_to "the region", region_path %> to get you started.</p>

<p>Before we start with how to get to places, let us give you the addresses for the most important locations:</p>
<div class="row">
	<div class="col-md-6">
		<p><strong>Venue Friday night: </strong><br>
		Weingut Ankermühle<br>
		Kapperweg 1<br>
		65375 Oestrich-Winkel</p>

		<p><strong>Church on Saturday:</strong><br>
		Evangelische Kirche Geisenheim<br>
		Winkeler Straße 83<br>
		65366 Geisenheim</p>

		<p><strong>Location for reception after church, celebrations Saturday evening and breakfast on Sunday morning:</strong><br>
		Burg Schwarzenstein<br>
		Rosengasse 32<br>
		65366 Geisenheim - Johannisberg<br></p>
	</div>
	<div class="col-md-4 col-md-offset-2">
		<%= image_tag("pic04.jpg", class: "right inline") %>
	</div>
</div>

<div>
	<iframe width=100% height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps/ms?msid=213619935787981326362.0004dd16626bc9fcb8416&amp;msa=0&amp;dg=feature&amp;ie=UTF8&amp;t=m&amp;ll=49.998912,7.975388&amp;spn=0.077241,0.205994&amp;z=12&amp;output=embed"></iframe><br />
	View <a href="https://maps.google.com/maps/ms?msid=213619935787981326362.0004dd16626bc9fcb8416&amp;msa=0&amp;dg=feature&amp;ie=UTF8&amp;t=m&amp;ll=49.998912,7.975388&amp;spn=0.077241,0.205994&amp;z=12&amp;source=embed">Wedding Locations</a> in a larger map
</div><br>

<p>Now, how do you get there:</p>

<p><strong>By air:</strong></p>

<p>For those of you planning to come by plane, you have the choice of flying into Frankfurt Main International Airport or Frankfurt Hahn Airport. </p>

<ul><li><p><a href="http://www.frankfurt-airport.com/content/frankfurt_airport/en.html">Frankfurt International Airport</a> is about 32 miles away and serviced by pretty much all big and known airlines. </p></li>

<li><p><a href="http://www.hahn-airport.de/">Frankfurt Hahn</a> is about 66 miles away and primarily serviced by Ryanair. 
</p></li></ul>

<p>Once you have made it to one of these airports, you can either choose to rent a car (see below) or try public transport. If you fly into Frankfurt Hahn, you'll probably have to get a car as the public transport connections from there are not great. </p>

<p>If you fly into Frankfurt International Airport and want to continue via public transport, you can do the following:
Take the <a href="http://www.rmv.de/en/">subway</a> S8 or S9 to Wiesbaden main station ("Wiesbaden Hauptbahnhof"). There change to the <a href="http://www.rheingaulinie.de/fahrplan">"Rheingau-Linie"</a>, which will take you all the way to the village the wedding will be in. The stop is called Geisenheim. </p>

<p>If you decide to rent a car from one of the airports, we recommend you do that through one of the main rental companies, <a href="http://www.hertz.com/">Hertz</a>, <a href="http://www.sixt.com/">Sixt</a> or <a href="http://www.europcar.com/">Europcar</a>.</p>

<p><strong>By train:</strong></p>
<p>If you decide to come by train, you'll probably want to aim for the main train stations in Frankfurt or Wiesbaden for the main part of your journey. Details on connections can be found <a href="http://www.bahn.com/i/view/GBR/en/index.shtml">here</a>.</p>

<p>At both stations, you can switch to the <a href="http://www.rheingaulinie.de/fahrplan">"Rheingau-Linie"</a>, which will take you all the way to the village the wedding will be in. The stop is called Geisenheim.</p>

<p><strong>By car: </strong></p>

<p>If you decide to come by car, we recommend you put the postcode and street name of your hotel or the church etc. into your SatNav and follow it. The postcodes in Germany are often for a much broader area than in the UK so you will need the street name too.</p>

<p>Once you have made it to the area of Geisenheim, you can use the maps provided above and on the hotels page to find your way around the local area. </p>

<p><strong>Local taxi companies:</strong></p>
<p>In case you need a taxi throughout the weekend, feel free to use the following details:</p>

<p>Taxi Locke: +49 (0) 6722 - 3333</p>
<p>Taxi Wagner: +49 (0) 177 - 5407973</p>